export interface IRegistration{
	company_id:number;
	company_name:string;
	login_id:string;
	password:string;
	customer_name:string;
	designation:string;
	email_id:string;
	address_line_1:string;
	address_line_2:string;
	city:string;
	state:string;
	pincode:number;
	company_tel:string;
	company_fax:string;
	holding:string;
	customer_tel:string;
	customer_mob:string;
	vat_no:string;
	pan_no:string
}